// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqmyTGKJcBJ9ggm2deU9a96efliMYGWXE',
    appId: '1:247396912566:web:0fb985fec87bdbf9e04517',
    messagingSenderId: '247396912566',
    projectId: 'kashta-39e72',
    authDomain: 'kashta-39e72.firebaseapp.com',
    storageBucket: 'kashta-39e72.firebasestorage.app',
    measurementId: 'G-XJ36XV1QDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKTs-1_0dcvpnq1rDQg3x-krtbyFZTYRA',
    appId: '1:247396912566:android:74296b8759558ca8e04517',
    messagingSenderId: '247396912566',
    projectId: 'kashta-39e72',
    storageBucket: 'kashta-39e72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuWJk2Dxq-K8sivnEmDQrtVVlXuE7e8SQ',
    appId: '1:247396912566:ios:80338eb58e13f184e04517',
    messagingSenderId: '247396912566',
    projectId: 'kashta-39e72',
    storageBucket: 'kashta-39e72.firebasestorage.app',
    iosClientId: '247396912566-nklb2lgc3bqkesgt0fr5m73gbhan8m6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.kashta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuWJk2Dxq-K8sivnEmDQrtVVlXuE7e8SQ',
    appId: '1:247396912566:ios:80338eb58e13f184e04517',
    messagingSenderId: '247396912566',
    projectId: 'kashta-39e72',
    storageBucket: 'kashta-39e72.firebasestorage.app',
    iosClientId: '247396912566-nklb2lgc3bqkesgt0fr5m73gbhan8m6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.kashta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqmyTGKJcBJ9ggm2deU9a96efliMYGWXE',
    appId: '1:247396912566:web:be478f4285c64d40e04517',
    messagingSenderId: '247396912566',
    projectId: 'kashta-39e72',
    authDomain: 'kashta-39e72.firebaseapp.com',
    storageBucket: 'kashta-39e72.firebasestorage.app',
    measurementId: 'G-P5ETBXFZDP',
  );

}